apiVersion: v1
kind: Namespace
metadata:
  name: ns-1
  labels:
    app: myapp

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: ns-1
  labels:
    app: myapp
    zone: stg
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
  restartPolicy: Always
---    
