apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: ns-1
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
